Named Glosses
CenterForDigitalHumanities/Glossing-Matthew pull request #14
Opened 2021-08-03 20:23 UTC by thehabes

2021-08-04 15:13 UTC, cubap requested changes
looking good. Let's see this with the gloss-alignment interface

2021-08-04 15:13 UTC, cubap commented on ng.html
> +            <input type="text" deer-key-todo="TODO" placeholder="Tags..." class="col-9 col-4-md">
We've used a tags widget before I think that would work here, but an array of strings would be fine too

2021-08-04 15:13 UTC, cubap commented on ng.html
> +            <input type="text" deer-key-todo="TODO" placeholder="Chapters..." class="col-9 col-4-md">
Just chapter and verse will be clear enough

2021-08-04 15:13 UTC, cubap commented on ng.html
> +            <input type="text" deer-key-todo="TODO" placeholder="T-PEN Lines..." class="col-9 col-4-md">
They will want some interface for selecting TPEN projects and then lines within them, so we would record all that stuff without direct annotation on a form like this.

In fact, it may be easier to duplicate the layout.html page with a form to add each line to a Gloss instead of selecting from the Gloss itself.

2021-08-04 16:37 UTC, thehabes commented on ng.html
> +            <input type="text" deer-key-todo="TODO" placeholder="Tags..." class="col-9 col-4-md">
Yeah, I think we did this for LRDA.  I will look and see, and default to an array of strings if there's a rabbit hole.

2021-08-04 16:37 UTC, thehabes commented on ng.html
> +            <input type="text" deer-key-todo="TODO" placeholder="Chapters..." class="col-9 col-4-md">
+1

2021-08-04 16:38 UTC, thehabes commented on ng.html
> +            <input type="text" deer-key-todo="TODO" placeholder="T-PEN Lines..." class="col-9 col-4-md">
This is the heart of it.  We will make a specific interface for picking lines and/or other properties (like manuscript)

2021-08-04 16:39 UTC, thehabes commented
Enhancements to come, thanks for the review @cubap

2021-08-05 20:44 UTC, thehabes commented
Ready for Review again.  Should be able to give it the final one-two punch during review, need to make a final decision on the UI.

2021-08-06 14:36 UTC, cubap approved these changes

2021-08-06 14:36 UTC, merged